export const products = [
  {
    id: 1,
    image: "../images/products/ligherMarkt.jpg",
    title: "Встраиваемый светильник Markt",
    oldPrice: "5 060",
    price: "3 490",
    sales: true,
  },
  {
    id: 2,
    image: "../images/products/ligherARG.jpg",
    title: "Линейный светильник ARG",
    price: "3 490",
    sales: false,
  },
  {
    id: 3,
    image: "../images/products/lighter.jpg",
    title: "Светодиодный светильник",
    oldPrice: "6 060",
    price: "5 060",
    sales: true,
  },
  {
    id: 4,
    image: "../images/products/ligherMarkt.jpg",
    title: "Встраиваемый светильник Markt",
    price: "3 490",
    sales: false,
  },
  {
    id: 5,
    image: "../images/products/ligherARG.jpg",
    title: "Линейный светильник ARG",
    oldPrice: "6 700",
    price: "6 060",
    sales: true,
  },
  {
    id: 6,
    image: "../images/products/lighter.jpg",
    title: "Сведодиодный светильник",
    price: "5 060",
    sales: false,
  },
  {
    id: 7,
    image: "../images/products/ligherMarkt.jpg",
    title: "Светодиодный светильник",
    oldPrice: "6 060",
    price: "3 490",
    sales: true,
  },
  {
    id: 8,
    image: "../images/products/ligherARG.jpg",
    title: "Линейный светильник ARG",
    price: "6 700",
    sales: false,
  },
];
